#!/bin/bash

# arguments are:
# 1    - number of cores
# 2    - outfile
# 3..N - input bams

if [[ "$#" -lt 3 ]]; then
    echo "not enough parameters specified. Expected numCores, outfile, and input_bams"
    exit 1
fi
#if there is only one bam, just copy it
if [[ "$#" -eq 3 ]]; then
    cp "$3" "$2"
else
    /usr/bin/sambamba merge -t $1 "$2" "${@:3}"
fi
